"""initial_schema

Revision ID: 20260616_0001
Revises: 
Create Date: 2026-06-16 21:05:58.359968
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '20260616_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metric_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('developer_count', sa.Integer(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('work_count', sa.Integer(), nullable=False),
    sa.Column('script_count', sa.Integer(), nullable=False),
    sa.Column('blog_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('service_count', sa.Integer(), nullable=False),
    sa.Column('deltas_json', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_metric_snapshots_snapshot_date'), 'daily_metric_snapshots', ['snapshot_date'], unique=True)
    op.create_table('service_execution_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('service_request_id', sa.String(length=96), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('step_name', sa.String(length=80), nullable=True),
    sa.Column('message_sanitized', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_execution_logs_created_at'), 'service_execution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_execution_logs_expires_at'), 'service_execution_logs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_service_execution_logs_service_request_id'), 'service_execution_logs', ['service_request_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=96), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('metadata_sanitized_json', sa.Text(), nullable=True),
    sa.Column('service_request_id', sa.String(length=96), nullable=True),
    sa.Column('source_ip_hash', sa.String(length=128), nullable=True),
    sa.Column('user_agent_summary', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_service_request_id'), 'audit_logs', ['service_request_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('allow_copy', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_created_by'), 'content_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_index(op.f('ix_content_items_type'), 'content_items', ['type'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_invite_codes_created_by'), 'invite_codes', ['created_by'], unique=False)
    op.create_index(op.f('ix_invite_codes_status'), 'invite_codes', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_ip_hash', sa.String(length=128), nullable=True),
    sa.Column('user_agent_summary', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moderated_by', sa.String(length=64), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_source_ip_hash'), 'messages', ['source_ip_hash'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('workstation_services',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('service_type', sa.String(length=32), nullable=False),
    sa.Column('script_key', sa.String(length=80), nullable=True),
    sa.Column('script_version', sa.String(length=80), nullable=True),
    sa.Column('input_schema_json', sa.Text(), nullable=False),
    sa.Column('result_display_mode', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workstation_services_created_by'), 'workstation_services', ['created_by'], unique=False)
    op.create_index(op.f('ix_workstation_services_script_key'), 'workstation_services', ['script_key'], unique=False)
    op.create_index(op.f('ix_workstation_services_status'), 'workstation_services', ['status'], unique=False)
    op.create_table('content_attachments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=120), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('allow_download', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_attachments_allow_download'), 'content_attachments', ['allow_download'], unique=False)
    op.create_index(op.f('ix_content_attachments_content_id'), 'content_attachments', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_attachments_uploaded_by'), 'content_attachments', ['uploaded_by'], unique=False)
    op.create_table('invite_code_usages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('invite_code_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip_hash', sa.String(length=128), nullable=True),
    sa.Column('user_agent_summary', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_code_usages_invite_code_id'), 'invite_code_usages', ['invite_code_id'], unique=False)
    op.create_index(op.f('ix_invite_code_usages_used_at'), 'invite_code_usages', ['used_at'], unique=False)
    op.create_index(op.f('ix_invite_code_usages_user_id'), 'invite_code_usages', ['user_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('service_request_id', sa.String(length=96), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('service_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('lumitime_user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=40), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('student_account_hash', sa.String(length=128), nullable=True),
    sa.Column('student_account_masked', sa.String(length=120), nullable=True),
    sa.Column('task_config_sanitized_json', sa.Text(), nullable=True),
    sa.Column('retry_of_service_request_id', sa.String(length=96), nullable=True),
    sa.Column('script_version', sa.String(length=80), nullable=True),
    sa.Column('source_ip_hash', sa.String(length=128), nullable=True),
    sa.Column('user_agent_summary', sa.String(length=180), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lumitime_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['workstation_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_request_id', name='uq_service_request_public_id')
    )
    op.create_index(op.f('ix_service_requests_created_at'), 'service_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_requests_expires_at'), 'service_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_service_requests_failure_code'), 'service_requests', ['failure_code'], unique=False)
    op.create_index(op.f('ix_service_requests_lumitime_user_id'), 'service_requests', ['lumitime_user_id'], unique=False)
    op.create_index(op.f('ix_service_requests_service_id'), 'service_requests', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_requests_service_request_id'), 'service_requests', ['service_request_id'], unique=True)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_index(op.f('ix_service_requests_student_account_hash'), 'service_requests', ['student_account_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_requests_student_account_hash'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_service_request_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_service_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_lumitime_user_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_failure_code'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_expires_at'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_created_at'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_invite_code_usages_user_id'), table_name='invite_code_usages')
    op.drop_index(op.f('ix_invite_code_usages_used_at'), table_name='invite_code_usages')
    op.drop_index(op.f('ix_invite_code_usages_invite_code_id'), table_name='invite_code_usages')
    op.drop_table('invite_code_usages')
    op.drop_index(op.f('ix_content_attachments_uploaded_by'), table_name='content_attachments')
    op.drop_index(op.f('ix_content_attachments_content_id'), table_name='content_attachments')
    op.drop_index(op.f('ix_content_attachments_allow_download'), table_name='content_attachments')
    op.drop_table('content_attachments')
    op.drop_index(op.f('ix_workstation_services_status'), table_name='workstation_services')
    op.drop_index(op.f('ix_workstation_services_script_key'), table_name='workstation_services')
    op.drop_index(op.f('ix_workstation_services_created_by'), table_name='workstation_services')
    op.drop_table('workstation_services')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_source_ip_hash'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_invite_codes_status'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_created_by'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_content_items_type'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_created_by'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_audit_logs_service_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_execution_logs_service_request_id'), table_name='service_execution_logs')
    op.drop_index(op.f('ix_service_execution_logs_expires_at'), table_name='service_execution_logs')
    op.drop_index(op.f('ix_service_execution_logs_created_at'), table_name='service_execution_logs')
    op.drop_table('service_execution_logs')
    op.drop_index(op.f('ix_daily_metric_snapshots_snapshot_date'), table_name='daily_metric_snapshots')
    op.drop_table('daily_metric_snapshots')
    # ### end Alembic commands ###
